package name.milesparker.epi.plague;

/**
 * <!-- begin-user-doc -->
 * Rat Style 2D Java Implementation.
 * 
 * Generated by AMF for model: EpidemicPlague.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class RatStyle2D {

}
