package org.eclipse.amp.examples.heatbugs;

import org.eclipse.amp.agf.IGraphicsAdapter;
import org.eclipse.amp.agf.GraphicsAdapter;
import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.core.runtime.IAdapterFactory;

import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.jface.viewers.IColorProvider;
import org.eclipse.jface.viewers.ILabelProvider;

/**
 * <!-- begin-user-doc -->
 * Heatbugs Java Implementation.
 * 
 * Generated by AMF for model: Heatbugs.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class HeatbugsGraphicsAdapter extends GraphicsAdapter {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static IGraphicsAdapter singleton;

	IColorProvider[] heatbugsColorProviders = new IColorProvider[]{};
	IColorProvider[] heatBugColorProviders = new IColorProvider[]{HeatBugStyle2DColorProvider
			.getDefault()};
	IColorProvider[] heatCellColorProviders = new IColorProvider[]{HeatCellStyle2DColorProvider
			.getDefault()};

	IFigureProvider[] heatbugsFigureProviders = new IFigureProvider[]{};
	IFigureProvider[] heatBugFigureProviders = new IFigureProvider[]{HeatBugStyle2DFigureProvider
			.getDefault()};
	IFigureProvider[] heatCellFigureProviders = new IFigureProvider[]{HeatCellStyle2DFigureProvider
			.getDefault()};

	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getColorsForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IColorProvider[] getColorsForClass(Class type) {
		if (type == Heatbugs.class) {
			return heatbugsColorProviders;
		}
		if (type == HeatBug.class) {
			return heatBugColorProviders;
		}
		if (type == HeatCell.class) {
			return heatCellColorProviders;
		}
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getFiguresForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IFigureProvider[] getFiguresForClass(Class type) {
		if (type == Heatbugs.class) {
			return heatbugsFigureProviders;
		}
		if (type == HeatBug.class) {
			return heatBugFigureProviders;
		}
		if (type == HeatCell.class) {
			return heatCellFigureProviders;
		}
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getLabelsForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ILabelProvider[] getLabelsForClass(Class type) {
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static IGraphicsAdapter getDefault() {
		if (singleton == null) {
			singleton = new HeatbugsGraphicsAdapter();
		}
		return singleton;
	}
}
