package org.eclipse.amp.examples.heatbugs;

/**
 * <!-- begin-user-doc -->
 * Heat Bug Style 2D Java Implementation.
 * 
 * Generated by AMF for model: Heatbugs.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class HeatBugStyle2D {

}
