package name.milesparker.epi.region;

/**
 * <!-- begin-user-doc -->
 * City Style 2D Java Implementation.
 * 
 * Generated by AMF for model: EpidemicRegional.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class CityStyle2D {

}
