package name.milesparker.epi.region;

import org.eclipse.amp.agf.IGraphicsAdapter;
import org.eclipse.amp.agf.GraphicsAdapter;
import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.core.runtime.IAdapterFactory;

import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.jface.viewers.IColorProvider;
import org.eclipse.jface.viewers.ILabelProvider;

/**
 * <!-- begin-user-doc -->
 * Region Java Implementation.
 * 
 * Generated by AMF for model: EpidemicRegional.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class RegionGraphicsAdapter extends GraphicsAdapter {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static IGraphicsAdapter singleton;

	IColorProvider[] regionColorProviders = new IColorProvider[]{};
	IColorProvider[] cityColorProviders = new IColorProvider[]{CityStyle2DColorProvider
			.getDefault()};
	IColorProvider[] individualColorProviders = new IColorProvider[]{IndividualStyle2DColorProvider
			.getDefault()};
	IColorProvider[] placeColorProviders = new IColorProvider[]{};
	IColorProvider[] regionalLocationColorProviders = new IColorProvider[]{};

	IFigureProvider[] regionFigureProviders = new IFigureProvider[]{};
	IFigureProvider[] cityFigureProviders = new IFigureProvider[]{CityStyle2DFigureProvider
			.getDefault()};
	IFigureProvider[] individualFigureProviders = new IFigureProvider[]{IndividualStyle2DFigureProvider
			.getDefault()};
	IFigureProvider[] placeFigureProviders = new IFigureProvider[]{};
	IFigureProvider[] regionalLocationFigureProviders = new IFigureProvider[]{};

	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getColorsForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IColorProvider[] getColorsForClass(Class type) {
		if (type == Region.class) {
			return regionColorProviders;
		}
		if (type == City.class) {
			return cityColorProviders;
		}
		if (type == Individual.class) {
			return individualColorProviders;
		}
		if (type == Place.class) {
			return placeColorProviders;
		}
		if (type == RegionalLocation.class) {
			return regionalLocationColorProviders;
		}
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getFiguresForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IFigureProvider[] getFiguresForClass(Class type) {
		if (type == Region.class) {
			return regionFigureProviders;
		}
		if (type == City.class) {
			return cityFigureProviders;
		}
		if (type == Individual.class) {
			return individualFigureProviders;
		}
		if (type == Place.class) {
			return placeFigureProviders;
		}
		if (type == RegionalLocation.class) {
			return regionalLocationFigureProviders;
		}
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getLabelsForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ILabelProvider[] getLabelsForClass(Class type) {
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static IGraphicsAdapter getDefault() {
		if (singleton == null) {
			singleton = new RegionGraphicsAdapter();
		}
		return singleton;
	}
}
