package name.milesparker.epi.region;

import org.eclipse.amp.escape.ascape.agf3d.GEF3DView;

/**
 * <!-- begin-user-doc -->
 * Region Java Implementation.
 * 
 * Generated by AMF for model: EpidemicRegional.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class Region3D extends Region {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void createGraphicViews() {
		addView(new GEF3DView());
	}
}
