package org.metaabm.examples.stupid3;

import org.eclipse.amp.escape.ascape.agf3d.GEF3DView;

/**
 * <!-- begin-user-doc -->
 * Stupid Model 3 Java Implementation.
 * 
 * Generated by AMF for model: StupidModel3.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class StupidModel33D extends StupidModel3 {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void createGraphicViews() {
		addView(new GEF3DView());
	}
}
