package org.eclipse.amp.amf.examples.escape;

/**
 * <!-- begin-user-doc -->
 * Simple Draw Java Implementation.
 * 
 * Generated by AMF for model: WikiExample.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class SimpleDraw {

}
