package org.eclipse.amp.amf.examples.escape;

import org.eclipse.amp.escape.ascape.agf3d.GEF3DView;

/**
 * <!-- begin-user-doc -->
 * WikiExample Java Implementation.
 * 
 * Generated by AMF for model: WikiExample.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class WikiExample3D extends WikiExample {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void createGraphicViews() {
		addView(new GEF3DView());
	}
}
