package org.eclipse.amp.amf.examples.escape;

import org.eclipse.core.runtime.IAdapterFactory;

import org.ascape.model.Scape;

import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.jface.viewers.IColorProvider;

/**
 * WikiExample Java Implementation.
 * 
 * Generated by AMF for model: WikiExample.metaabm in project: org.eclipse.amp.amf.examples.escape 
 */

public class WikiExampleAdapterFactory implements IAdapterFactory {

	private static IAdapterFactory singleton;

	Class[] adapters = new Class[]{IFigureProvider.class, IColorProvider.class};

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @see org.eclipse.core.runtime.IAdapterFactory#getAdapter(java.lang.Object, java.lang.Class)
	 */
	public Object getAdapter(Object agent, Class type) {
		if (type == IColorProvider.class) {

			if (agent instanceof Scape
					&& ((Scape) agent).getPrototypeAgent().getClass() == Individual.class) {
				return org.eclipse.amp.amf.examples.escape.SimpleDrawColorProvider
						.getDefault();
			}

		}

		if (type == IFigureProvider.class) {

			if (agent instanceof Scape
					&& ((Scape) agent).getPrototypeAgent().getClass() == Individual.class) {
				return org.eclipse.amp.amf.examples.escape.SimpleDrawFigureProvider
						.getDefault();
			}

		}

		return null;
	}

	/**
	 * @return
	 * @see org.eclipse.core.runtime.IAdapterFactory#getAdapterList()
	 */
	public Class[] getAdapterList() {
		return adapters;
	}

	public static IAdapterFactory getDefault() {
		return singleton;
	}
}
