package name.milesparker.markets;

/**
 * <!-- begin-user-doc -->
 * Instrument Style 2D Java Implementation.
 * 
 * Generated by AMF for model: Markets.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class InstrumentStyle2D {

}
