package name.milesparker.markets;

import org.eclipse.amp.agf.IGraphicsAdapter;
import org.eclipse.amp.agf.GraphicsAdapter;
import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.core.runtime.IAdapterFactory;

import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.jface.viewers.IColorProvider;
import org.eclipse.jface.viewers.ILabelProvider;

/**
 * <!-- begin-user-doc -->
 * Markets Java Implementation.
 * 
 * Generated by AMF for model: Markets.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class MarketsGraphicsAdapter extends GraphicsAdapter {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static IGraphicsAdapter singleton;

	IColorProvider[] marketsColorProviders = new IColorProvider[]{};
	IColorProvider[] traderColorProviders = new IColorProvider[]{TraderStyle2DColorProvider
			.getDefault()};
	IColorProvider[] firmColorProviders = new IColorProvider[]{FirmStyle2DColorProvider
			.getDefault()};
	IColorProvider[] instrumentColorProviders = new IColorProvider[]{InstrumentStyle2DColorProvider
			.getDefault()};

	IFigureProvider[] marketsFigureProviders = new IFigureProvider[]{};
	IFigureProvider[] traderFigureProviders = new IFigureProvider[]{TraderStyle2DFigureProvider
			.getDefault()};
	IFigureProvider[] firmFigureProviders = new IFigureProvider[]{FirmStyle2DFigureProvider
			.getDefault()};
	IFigureProvider[] instrumentFigureProviders = new IFigureProvider[]{InstrumentStyle2DFigureProvider
			.getDefault()};

	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getColorsForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IColorProvider[] getColorsForClass(Class type) {
		if (type == Markets.class) {
			return marketsColorProviders;
		}
		if (type == Trader.class) {
			return traderColorProviders;
		}
		if (type == Firm.class) {
			return firmColorProviders;
		}
		if (type == Instrument.class) {
			return instrumentColorProviders;
		}
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getFiguresForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IFigureProvider[] getFiguresForClass(Class type) {
		if (type == Markets.class) {
			return marketsFigureProviders;
		}
		if (type == Trader.class) {
			return traderFigureProviders;
		}
		if (type == Firm.class) {
			return firmFigureProviders;
		}
		if (type == Instrument.class) {
			return instrumentFigureProviders;
		}
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getLabelsForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ILabelProvider[] getLabelsForClass(Class type) {
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static IGraphicsAdapter getDefault() {
		if (singleton == null) {
			singleton = new MarketsGraphicsAdapter();
		}
		return singleton;
	}
}
