package edu.brook;

/**
 * <!-- begin-user-doc -->
 * Cooperate Defect Style Java Implementation.
 * 
 * Generated by AMF for model: DemographicPrisoner_sDilemma.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class CooperateDefectStyle {

}
