package edu.brook;

import org.eclipse.core.runtime.IAdapterFactory;

import org.ascape.model.Scape;

import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.jface.viewers.IColorProvider;

/**
 * Demographic Prisoner_s Dilemma Java Implementation.
 * 
 * Generated by AMF for model: DemographicPrisoner_sDilemma.metaabm in project: org.eclipse.amp.amf.examples.escape 
 */

public class DemographicPrisonersDilemmaAdapterFactory
		implements
			IAdapterFactory {

	private static IAdapterFactory singleton;

	Class[] adapters = new Class[]{IFigureProvider.class, IColorProvider.class};

	/**
	 * @param arg0
	 * @param arg1
	 * @return
	 * @see org.eclipse.core.runtime.IAdapterFactory#getAdapter(java.lang.Object, java.lang.Class)
	 */
	public Object getAdapter(Object agent, Class type) {
		if (type == IColorProvider.class) {

			if (agent instanceof Player) {
				return edu.brook.CooperateDefectStyleColorProvider.getDefault();
			}

			if (agent instanceof PlayCell) {
				return edu.brook.PlayCellStyleColorProvider.getDefault();
			}

		}

		if (type == IFigureProvider.class) {

			if (agent instanceof Player) {
				return edu.brook.CooperateDefectStyleFigureProvider
						.getDefault();
			}

			if (agent instanceof PlayCell) {
				return edu.brook.PlayCellStyleFigureProvider.getDefault();
			}

		}

		return null;
	}

	/**
	 * @return
	 * @see org.eclipse.core.runtime.IAdapterFactory#getAdapterList()
	 */
	public Class[] getAdapterList() {
		return adapters;
	}

	public static IAdapterFactory getDefault() {
		if (singleton == null) {
			singleton = new DemographicPrisonersDilemmaAdapterFactory();
		}
		return singleton;
	}
}
