package edu.brook;

/**
 * <!-- begin-user-doc -->
 * Play Cell Style 2D Java Implementation.
 * 
 * Generated by AMF for model: DemographicPrisoner_sDilemma.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class PlayCellStyle {

}
