package org.metaabm.examples.stupid5;

import org.eclipse.amp.escape.ascape.agf3d.GEF3DView;

/**
 * <!-- begin-user-doc -->
 * Stupid Model 5 Java Implementation.
 * 
 * Generated by AMF for model: StupidModel5.metaabm in project: org.eclipse.amp.amf.examples.escape 
 * <!-- end-user-doc -->
 * @generated
 */
public class StupidModel53D extends StupidModel5 {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void createGraphicViews() {
		addView(new GEF3DView());
	}
}
